region                      = "us-east-1"
az_ids                      = ["use1-az1", "use1-az2"]
cluster_number              = 1
vpc_nodes_cidr              = "10.0.0.0/17"
cluster_subnet_mask_len     = 24
ctrl_plan_cidr              = "10.1.128.0/20"
ctrl_plan_subnet_mask_len   = 27
vpc_cidr_for_public_subnet  = "10.2.192.0/20"
public_subnet_mask_len      = 27
name_tag_prefix             = "Cool-App"
